[workspace]
resolver = "3"

members = [
    "drivers/driver_traits",
    "drivers/gpio/*",
    "drivers/uart/*",
    "sharkfin_kernel",
    "kernel_utils"
, "devices/*", "drivers/clock/*", "arch/aarch64/*"]

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
